version: '3'
services:
  jupyter:
    image: jupyter/datascience-notebook
    # Expose 80 and map to 8888 internal port (default)
    ports:
      - "80:8888"
    volumes:
      # mount the ./notebooks directory to work folder
      - ./notebooks:/home/jovyan/work
    environment:
      - "JUPYTER_ENABLE_LAB=yes"
  database:
    image: "postgres" # use latest official postgres version
    # expose port 5432
    ports:
      - "5432:5432"
    env_file:
      - config/database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

# named volumes
volumes:
  database-data:
